.global trap
.global TrapHandler

.align 16

trap:
addi sp, sp, -272 #zaokruzuje se na broj deljiv sa 16
#po zahtevu sp mora biti deljiv sa 16

sd t0, 168(sp)

csrr t0, sepc #pc pre ecall
sd t0, 248(sp)
csrr t0, sstatus #statusni registar pre ecall
sd t0, 256(sp)

sd ra, 0(sp)
sd s0, 8(sp)
sd s1, 16(sp)
sd s2, 24(sp)
sd s3, 32(sp)
sd s4, 40(sp)
sd s5, 48(sp)
sd s6, 56(sp)
sd s7, 64(sp)
sd s8, 72(sp)
sd s9, 80(sp)
sd s10, 88(sp)
sd s11, 96(sp)
sd a0, 104(sp)
sd a1, 112(sp)
sd a2, 120(sp)
sd a3, 128(sp)
sd a4, 136(sp)
sd a5, 144(sp)
sd a6, 152(sp)
sd a7, 160(sp)
sd t1, 176(sp)
sd t2, 184(sp)
sd t3, 192(sp)
sd t4, 200(sp)
sd t5, 208(sp)
sd t6, 216(sp)
sd gp, 224(sp)
sd tp, 232(sp)

addi t0, sp, 272
sd t0, 240(sp)

mv a0, sp #kao argument trap handleru se salje sp, to omogucava iteraciju kroz niz registara
call TrapHandler
sd a0, 104(sp)

ld t0, 256(sp)
csrw sstatus, t0
ld t0, 248(sp)
addi t0, t0, 4 #prelazak na instrukciju nakon ecall
csrw sepc, t0

ld ra, 0(sp)
ld s0, 8(sp)
ld s1, 16(sp)
ld s2, 24(sp)
ld s3, 32(sp)
ld s4, 40(sp)
ld s5, 48(sp)
ld s6, 56(sp)
ld s7, 64(sp)
ld s8, 72(sp)
ld s9, 80(sp)
ld s10, 88(sp)
ld s11, 96(sp)
ld a0, 104(sp)
ld a1, 112(sp)
ld a2, 120(sp)
ld a3, 128(sp)
ld a4, 136(sp)
ld a5, 144(sp)
ld a6, 152(sp)
ld a7, 160(sp)
ld t1, 176(sp)
ld t2, 184(sp)
ld t3, 192(sp)
ld t4, 200(sp)
ld t5, 208(sp)
ld t6, 216(sp)
ld gp, 224(sp)
ld tp, 232(sp)
ld sp, 240(sp)

sret